#+SETUPFILE: ~/.emacs.d/org-templates/template.org
#+TITLE: Bash

* жЈҖжөӢж–Үд»¶жҲ–зӣ®еҪ•жҳҜеҗҰеӯҳеңЁ
#+BEGIN_SRC shell :results output
  if [ -f "/root/.zshrc" ];
  then
      echo "~/.zshrc exists"
  else
      echo "~/.zshrc not exists"
  fi
#+END_SRC

#+RESULTS:
: ~/.zshrc exists


#+BEGIN_SRC shell :results output
  if [ -d "/root/.emacs.d" ];
  then
      echo "/root/.emacs.d exists"
  else
      echo "/root/.emacs.d not exists"
  fi
#+END_SRC

#+RESULTS:
: /root/.emacs.d exists

#+BEGIN_SRC shell :results output
  if [[ -d "/root/.emacs.d" && -d "/root/.vim" ]];
  then
      echo "/root/.emacs.d and /root/.vim exists"
  else
      echo "/root/.emacs.d or /root/.vim not exists"
  fi
#+END_SRC

#+RESULTS:
: /root/.emacs.d and /root/.vim exists


#+BEGIN_SRC shell :results output
  if [[ -d "/root/.emacs.d" || -d "/root/.vimhaha" ]];
  then
      echo "/root/.emacs.d or /root/.vimhaha exists"
  else
      echo "/root/.emacs.d and /root/.vim not exists"
  fi
#+END_SRC

#+RESULTS:
: /root/.emacs.d or /root/.vim exists


#+BEGIN_SRC shell :results output
  if [ -d "/root/.emacs.d" -a -d "/root/.vim" ];
  then
      echo "/root/.emacs.d and /root/.vim exists"
  else
      echo "/root/.emacs.d or /root/.vim not exists"
  fi

#+END_SRC

#+RESULTS:
: /root/.emacs.d and /root/.vim exists

** е…¶е®ғж“ҚдҪң
#+BEGIN_VERSE
1. -b FILE: True if exists and is a block special file
2. -c FILE: True if exists and is as special character file
3. -d FILE: True if exists and is as directory
4. -f FILE: True if exists and is a regular file
5. -G FILE: True if exists and has the same group as the user running the command.
6. -h/-L File: True if the FILE exists and is a symbolic link.
7. -g FILE: True if the FILE exists and has set-group-id flag set.
8. -k FILE: True if the FILE exists and has as sticky bit flag set.
9. -O FILE: True if the FILE exists and is owned by the user runnig the command.
10. -p FILE: True if the FILE exists and is a pipe
11. -r FILE: True if the FILE exists and is readable.
12. -S FILE: True if the FILE exists and is a socket
13. -s FILE: True if the FILE exists and has a nonzero size.
14. -u FILE: True if the FILE exists and set-user-id flag is set.
15. -w FILE: True if the FILE exists and is writable.
16. -x FILE: True if the FILE exists and is executable.
#+END_VERSE
* ж•°з»„
** initial and access
#+begin_src shell
  array=(30 10 2 9 4 5)
  echo ${array}
  echo ${array[*]}
  echo ${array[@]}
  echo ${array[1]} # дёҚжҳҜд»Ҙ0дҪңдёәејҖе§Ӣ
  echo ${array[-1]}
#+end_src

#+RESULTS:
| 30 | 10 | 2 | 9 | 4 | 5 |
| 30 | 10 | 2 | 9 | 4 | 5 |
| 30 | 10 | 2 | 9 | 4 | 5 |
| 30 |    |   |   |   |   |
|  5 |    |   |   |   |   |
** append
#+begin_src shell
  array=(1 2 3 4 5)
  array+=("hello")
  array+=("python")
  echo ${array}
#+end_src

#+RESULTS:
: 1 2 3 4 5 hello python

** delete
#+begin_src shell
  array=(1 2 3 4)
  delete=3
  array=( "${array[@]/$delete}" )
  echo ${array}
#+end_src

#+RESULTS:
: 1 2 4

** iterator
#+begin_src shell
  #!/bin/bash
  array=(1 9 10 8 7)
  echo ${array[@]:1:2}
#+end_src

#+RESULTS:
: 9 10

#+begin_src shell
  array=(1 2 9 4 5)
  for t in ${array[@]}; do
      echo ${t}
  done
#+end_src

#+RESULTS:
| 1 |
| 2 |
| 9 |
| 4 |
| 5 |

** length
#+begin_src shell
  array=(1 2 3 4 5)
  echo "ж•°з»„е…ғзҙ дёӘж•°дёә: ${#array[*]}"
  echo "ж•°з»„е…ғзҙ дёӘж•°дёә: ${#array[@]}"
#+end_src

#+RESULTS:
| ж•°з»„е…ғзҙ дёӘж•°дёә: | 5 |
| ж•°з»„е…ғзҙ дёӘж•°дёә: | 5 |

* getopts
1. =getopt -o f:s::d:a::= :
   1. -o еҗҺйқўдёҖдёІиЎЁзӨәеҸҜд»ҘжҺҘзҹӯйҖүйЎ№,еҰӮ-f,-s
   2. еҰӮжһңеӯ—з¬ҰеҗҺйқўеҸӘжңүдёҖдёӘ':', еҰӮ 'f:' 'd:' иЎЁзӨәеҸӮж•°еҝ…йЎ»дј 
   3. еҰӮжһңеӯ—з¬ҰеҗҺйқўжңүдёӨдёӘ':', еҰӮ 's::' 'a::' иЎЁзӨәеҸӮж•°жҳҜеҸҜйҖүзҡ„
2. =--long file-name:,source::,destination:,action::= :
   1. --long еҗҺйқўжҺҘзҡ„жҳҜй•ҝйҖүйЎ№,еҰӮ --file-name, --source
   2. еҗҺйқўжҺҘ дёҖдёӘ ':', дёӨдёӘ ':' е’ҢзҹӯйҖүйЎ№зӣёеҗҢ

#+begin_src shell
  #!/bin/bash

  # read the options
  TEMP=`getopt -o f:s::d:a:: --long file-name:,source::,destination:,action:: -- "$@"`
  eval set -- "$TEMP"

  # extract options and their arguments into variables.
  while true ; do
      case "$1" in
          -f|--file-name)
              fileName=$2
              shift 2 ;;
          -s|--source)
              case "$2" in
                  "")
                      sourceDir='.'
                      shift 2 ;;
                  ,*)
                      sourceDir=$2
                      shift 2 ;;
              esac ;;
          -d|--destination)
              destinationDir=$2
              shift 2;;
          -a|--action)
              case "$2" in
                  "copy"|"move")
                      action=$2
                      shift 2 ;;
                  ,*)
                      action="copy"
                      shift 2 ;;
              esac ;;
          --)
              shift
              break ;;
          ,*)
              echo "Internal error!"
              exit 1 ;;
      esac
  done

  # Now take action
  echo "$action file $fileName from $sourceDir to $destinationDir"
#+end_src
