#+SETUPFILE: ~/.emacs.d/org-templates/template.org
#+TITLE: Dockerfile Reference
#+DATE: Sat 05 Jun 2021 01:17:51 AM CST


* Dockerfile Reference
[[https://docs.docker.com/engine/reference/builder/][Dockerfile Reference]]
* Dockerfile
一个Dockerfile必须以 *FROM* 作为第一条指令,用于指明父镜像
* Parser Directives
#+BEGIN_VERSE
*Parser Directive* 必须出现在 Dockerfile 的最前面.其后面的第一条指令与其有一个空行.其它地方出现的 Directive 被视作注释
目前一共支持两种 *Parser Directive*
1. syntax
2. escape
#+END_VERSE

1. syntax
   #+BEGIN_SRC dockerfile
     # syntax=docker/dockerfile:1
     # syntax=docker.io/docker/dockerfile:1
     # syntax=example.com/user/repo:tag@sha256:abcdef...
   #+END_SRC
   #+BEGIN_VERSE
   这个语法只有在 *bukldkit* 作为后端的情况下才有效.
   这个短语的作用是指明Dockerfile的语法
   #+END_VERSE
2. escape
   #+BEGIN_SRC dockerfile
     # escape=\ (backslash)
     # escape=` (backtick)
   #+END_SRC
   #+BEGIN_VERSE
   这个短语用于设置Dockerfile中的转义字符,如果不声明默认为 '\'
   #+END_VERSE
* 环境变量
环境变量的使用语法如下:
1. $variable_name
2. ${variable_name}
3. ${variable:-word}: 如果variable未被设置,那么word就被设置为它的值
4. ${variable:+word}: 如果variable有被设置,那么word就被设置为它的值

*注: 环境变量的赋值
def被设置为hello,ghi被设置为bye.
#+BEGIN_SRC dockerfile
  ENV abc=hello
  ENV abc=bye def=$abc
  ENV ghi=$abc
#+END_SRC
* 语法
** FROM
#+BEGIN_EXAMPLE
  FROM [--platform=<platform>] <image> [AS <name>]
  FROM [--platform=<platform>] <image>[:<tag>] [AS <name>]
  FROM [--platform=<platform>] <image>[@<digest>] [AS <name>]
#+END_EXAMPLE
*FROM* 用于设置后面的指令的基础镜像.

1. FROM 必须出现在除ARG外的其它的指令的前面
2. 同一个Dockerfile中可以有多个FROM出现.主要用于:
   1. 同时创建多个镜像
   2. 一个镜像作为另一个镜像的依赖的时候
3. 用 AS name 为镜像赋一个名字,后面指令可以用 --from=<name> 来引用
4. tag,digest为可选项,如果不设置则为 latest
*** FROM 前面的 ARG
#+BEGIN_SRC dockerfile
  ARG  CODE_VERSION=latest
  FROM base:${CODE_VERSION}
  CMD  /code/run-app

  FROM extras:${CODE_VERSION}
  CMD  /code/run-extras
#+END_SRC

#+BEGIN_VERSE
FROM前面的ARG字义的变量只可以在FROM中使用,不能在其它指令中使用,
如果想在后面的指令中使用FROM前面定义的变量需要重新声明一次这个变量,但是不为其赋值
#+END_VERSE

#+BEGIN_SRC dockerfile
  ARG VERSION=latest
  FROM busybox:$VERSION
  ARG VERSION
  RUN echo $VERSION > image_version
#+END_SRC
** RUN
#+BEGIN_EXAMPLE
  1. RUN <command>: shellform
  2. RUN ["executable", "param1", "param2" ...]: execform
#+END_EXAMPLE

#+BEGIN_VERSE
execform不会解释环境变量,如:
#+END_VERSE
#+BEGIN_EXAMPLE
RUN ["echo", "$HOME"]
#+END_EXAMPLE
#+BEGIN_VERSE
中的$HOME会原样输出成$HOME
#+END_VERSE
#+BEGIN_EXAMPLE
  RUN ["sh", "-c", "echo $HOME"]
#+END_EXAMPLE
#+BEGIN_VERSE
则会正常解释$HOME为容器当前家目录
#+END_VERSE
** CMD
#+BEGIN_EXAMPLE
  CMD ["executable","param1","param2"] # execform
  CMD ["param1", "param2"] # 作为 ENTRYPOINT 的默认参数
  CMD command param1 param2 # shellform
#+END_EXAMPLE
#+BEGIN_VERSE
一个Dockerfile中只有一个CMD是有效的,如果有多个CMD,只有最后一个生效.
CMD 的一个主要作用是为了容器提供预设值,这个预设值可以包含或者不包含可执行文件,如果不包含可执行文件,那么就必须要提供 ENTRYPOINT
如果 CMD 是为了 ENTRYPOINT提供参数,那么 CMD,ENTRYPOINT都要以数组的形式提供
如果使用 docker run 的时候提供了指定的参数,那么 CMD 将被忽略
#+END_VERSE
** LABEL
#+BEGIN_EXAMPLE
LABEL <key>=<value> <key>=<value> ...
#+END_EXAMPLE
#+BEGIN_VERSE
LABEL 的作用是为镜像添加元信息
元信息可以从父镜像处继承
通过 *docker image inspect --format='' image* 查看镜像的labels
#+END_VERSE
** EXPOSE
#+BEGIN_EXAMPLE
EXPOSE <port> [<port>/<protocol>...]
#+END_EXAMPLE
#+BEGIN_VERSE
EXPOSE告诉容器,这些端口可以被外部使用.默认protocol是TCP.
它主要是用于镜像创建者告诉使用者,哪些端口倾向于被使用,但是实际还是在 docker run 的时候使用 -p 参数 来指定容器对外开放的端口
#+END_VERSE
** ENV
#+BEGIN_EXAMPLE
ENV <key>=<value> ...
#+END_EXAMPLE
#+BEGIN_VERSE
ENV 用于设置容器运行时的环境变量.ENV设置的环境变量在镜像阶段,容器阶段都是有效的.与ARG不同的是,ARG只在镜像阶段有效
使用 /docker run --env <key>=<value>/ 来覆盖dockerfile中的env的值
#+END_VERSE

#+BEGIN_VERSE
如果一个变量要引用前面定义的变量,必须要用多个ENV来做设置,如:
#+END_VERSE
#+BEGIN_EXAMPLE
1. B => 空字符串
  ENV A=hello B=$A
2. B => hello
ENV A=hello
ENV B=$A
#+END_EXAMPLE
** ADD
#+BEGIN_EXAMPLE
  ADD [--chown=<user>:<group>] <src> ... <dest>
  ADD [--chown=<user>:<group>] ["src",..."<dest>"]
#+END_EXAMPLE
#+BEGIN_VERSE
src可以是文件,目录,也可以是网络地址
如果有指明 user/group 但是容器中不存在这个 user/group,那么 ADD 命令将失败
1. src 必须是以上下文根目录为起始目录
2. 如果 dest 是由 '/' 结尾的,那么下载的文件将放到 dest 目录下.否则下载的文件将保存为 dest 文件
3. 如果 src 是可识别的压缩文件,在ADD的时候,它将被解压
#+END_VERSE
