#+SETUPFILE: ~/.emacs.d/org-templates/template.org
#+TITLE: kafka

* 相关术语

- message:
  #+begin_verse
  对于Kafka而言,message就是字节数组外.一个message可以有一个可选的key,也是字节数组.key的主要作用是在message被分配partitions时,
  用于确定message保存在哪个partition.
  #+end_verse
- batch:
  #+begin_verse
  一组message.减少网络间数据交换的开销,会以batch的方式同时传递多个message.
  #+end_verse
- schema:
  #+begin_verse
  发送给kafka的数据和接收到数据需要遵循一定的规则.并且是比较稳定的规则,这样能提高应用层的稳定性.
  这个主要用于对接kafka服务的库需要重要了解.
  #+end_verse
- topic:
  #+begin_verse
  一条message属于一个topic.一个topic里面包含了一组相同类别的message.
  #+end_verse
- partition:
  #+begin_verse
  一个topic可能被保存在多个partition中.同一个partition中,可以保证消息被顺序消费,
  不同partition中,即使属于相同的topic的message也无法被保证按顺序消费
  #+end_verse
- producer
- consumer
- group
  #+begin_verse
  一个或多个consumer通过组成一个group.一个topic的某一个partition同一时间只能被一个组中的一个consumer消费
  #+end_verse
- broker
  #+begin_verse
  一个Kafka服务叫作broker.多个broker组成一个cluster.
  一个topic的某一个partition可以属于多个broker.
  其中一个broker-partition属于leader地位,其它的broker-partition则属于从属地位,
  主要用于从leader中同步message.
  #+end_verse
