#+SETUPFILE: ~/.emacs.d/org-templates/template.org
#+TITLE: Nginx

* 登陆认证
1. 安装密码生成工具: *apache2-utils* on (Debian, Ubuntu) *httpd-tools* on (RHEL/CentOS/Oracle Linux).
2. sudo htpasswd -c /etc/nginx/auth/.htpasswd username
3. 可以设置在location块,也可以设置在server块中.

#+BEGIN_SRC ini
  location /api {
      auth_basic           “Administrator’s Area”;
      auth_basic_user_file /etc/nginx/auth/.htpasswd;
  }
#+END_SRC

#+BEGIN_SRC ini
  server {
      auth_basic           "Administrator’s Area";
      auth_basic_user_file /etc/nginx/auth/.htpasswd;

      location /public/ {
          auth_basic off; # 关闭认证
      }
  }
#+END_SRC

* 开放目录浏览
1. autoindex on/off: 是否可以浏览目录
2. autoindex_exact_size on/off: 是否显示文件实际大小
3. autoindex_format html: 页面呈现的样式.json,xml,html,jsonp.
4. autoindex_lacaltime on/off: on时显示客户端本地时间.off时显示utc时间.
5. 同时记录把nginx的user(默认为www-data)对相应目录有访问权限

#+BEGIN_SRC ini
  location /somedirectory/ {
      autoindex on;
      autoindex_exact_size off;
      autoindex_format html;
      autoindex_localtime on;
  }
#+END_SRC

* 日志
** 参数
1. $remote_addr: 客户端地址
2. $remote_user: 客户端用户名称
3. $time_local: 访问时间和时区
4. $request: 请求的URI和HTTP协议
5. $http_host: 请求地址，即浏览器中你输入的地址（IP或域名）
6. $status: HTTP请求状态
7. $upstream_status: upstream状态
8. $body_bytes_sent: 发送给客户端文件内容大小
9. $http_referer: url跳转来源
10. $http_user_agent: 用户终端浏览器等信息
11. $ssl_protocol: SSL协议版本
12. $ssl_cipher: 交换数据中的算法
13. $upstream_addr: 后台upstream的地址，即真正提供服务的主机地址
14. $request_time: 整个请求的总时间
15. $upstream_response_time: 请求过程中，upstream响应时间

** 配置实例
#+BEGIN_SRC nginx
  log_format  main  '$request_time $upstream_response_time $remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"';
  access_log logs/access.log. main;

  log_format  main  '"$request_time" "$upstream_response_time" $remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"';

  access_log  /home/shilai/data/logs/nginx/access.log main;
#+END_SRC
