#+SETUPFILE: ~/.emacs.d/org-templates/template.org
#+PROPERTY: header-args    :results silent
#+TITLE: APUE Chapter 4 - Files and Directories

* Functions
** stat fstat fstatat lstat
#+begin_src C
  #include <sys/stat.h>
  int stat(const char *restrict pathname, struct stat *restrict buf);
  int fstat(int fd, struct stat *buf);
  int lstat(const char *restrict pathname, struct stat *restrict buf);
  int fstatat(int fd, const char *restrict pathname, struct stat *restrict buf, int flag);
#+end_src
Giving a pathname, the stat function returns a structure of information about the named file. The fstat function obtains
information abount the file that is already open on the descriptor fd. The lstat function is similar to stat, but when
the named file is a symbolic link, lstat returns information about the symbloci link.

The fstatat function.
1. If pathname is an absolute pathname, then the fd argument is ignored.
2. If pathname is a relative pathname, and the fd has the value AT_FDCWD, the fstatat evaluates the pathname argument
   relative to the current directory
3. If pathanem is a relative pathname, and the fd points to a directory, the fstatat evaluates the pathname argument
   relative to the fd directory.
4. If flag's value is AT_SYMLINK_NOFOLLOW and the pathname is a symbolic link, the fstatat returns the information of
   the symbolic link.

The file's information stores in the stat structure.
#+begin_src C
  struct stat {
      mode_t st_mode; // file type & mode(permission)
      ino_t st_ino; // i-node number
      dev_t st_dev; // device number
      dev_t st_rdev; // device number for special files
      nlink_t st_nlink; // number of links
      uid_t st_uid; // user ID of owner
      git_t st_gid; // group ID of owner
      off_t st_size; // size of bytes for regular files
      struct timespec st_atim; // time of last access
      struct timespec st_mtim; // time of last modification
      struct timespec st_ctim; // time of last file status change
      blksize_t st_blksize; // best I/O block size
      blkcnt_t st_blocks; // number of disk blocks allocated
  };

  struct timespec {
      time_t tv_sec; // seconds
      long tv_nsec; // nanoseconds
  };
#+end_src

1. S_ISGER(stat.st_mode): Check if regular file
2. S_ISDIR(stat.st_mode): Check if directory
3. S_ISCHR(stat.st_mode): Check if character special file
4. S_ISBLK(stat.st_mode): Check if block special file
5. S_ISFIFO(stat.st_mode): Check if pipe or FIFO
6. S_ISLNK(stat.st_mode): Check if symbolic link
7. S_ISSOCK(stat.st_mode): Check if socket
8. S_TYPEISMQ(stat): Check if message queue
9. S_TYPEISSEM(stat): Check if semaphore
10. S_TYPEISSHM(stat): Check if shared memory object.
** access faccessat
#+begin_src C
  #include <unistd.h>
  int access(const char *pathname, int mode);
  int faccessat(int fd, const char *pathname, int mode, int flag);
#+end_src
This functions check if the owner of the process can access the file.
1. mode:
   1. R_OK: test for read permission
   2. W_OK: test for write permission.
   3. X_OK: test for execute permission.
2. flag: If the AT_EACCESS flag is set, the access checks are made using the effective user and group IDs of the calling
   process instead of the real user and group IDs.
** umask
#+begin_src C
  #include <sys/stat.h>
  mode_t umask(mode_t cmask);
#+end_src
A File has nine access permissions:
| st_mode mask | Meaning       |
|--------------+---------------|
| S_IRUSR      | user-read     |
| S_IWUSR      | user-write    |
| S_IXUSR      | user-execute  |
| S_IRGRP      | group-read    |
| S_IWGRP      | group-write   |
| S_IXGRP      | group-execute |
| S_IROTH      | other-read    |
| S_IWOTH      | other-write   |
| S_IXOTH      | other-execute |
The umask function sets the file mode creation mask for the process and returns the previous value.
** chmod fchmod fchmodat
#+begin_src C
  #include <sys/stat.h>
  int chmod(const char *pathname, mode_t mode);
  int fchmod(int fd, mode_t mode);
  int fchmodat(int fd, const char *pathname, mode_t mode, int flag);
#+end_src
| mode      | Description                                |
|-----------+--------------------------------------------|
| S_ISUID   | set-user-ID on execution                   |
| S_ISGID   | set-group-ID on execution                  |
| S_ISVTX   | saved-text sticky bit                      |
| S_IRWXU   | read,write and execute by user(file owner) |
| \_S_IRUSR | read by user                               |
| \_S_IWUSR | write by user                              |
| \_S_IXUSR | execute by user                            |
| S_IRWXG   | read write and execute by grou             |
| \_S_IRGRP | read by group                              |
| \_S_IWGRP | write by group                             |
| \_S_IXGRP | execute by grou                            |
| S_IRWXO   | read,write and execute by other            |
| \_S_IROTH | read by other                              |
| \_S_IWOTH | write by other                             |
| \_S_IXOTH | execute by other                           |
If flag's value is AT_SYMLINK_NOFOLLOW and pathname is a symbolic link, the fchmodat will change the symbolic link's
permission, not the file that the symbolic link refers to.
** chown fchown fchownat lchown
#+begin_src C
  #include <unistd.h>
  int chown(const char *pathname, uid_t owner, gid_t group);
  int fchown(int fd, uid_t owner, gid_t group);
  int fchownat(int fd, const char *pathname, uid_t owner, gid_t group, int flag);
  int lchown(const char *pathname, uid_t owner, gid_t group);
#+end_src
These functions are used to change the file's user ID and group ID.
** truncate ftruncate
#+begin_src C
  #include <unistd.h>
  int truncate(const char *pathname, off_t length);
  int ftruncate(int fd, off_t length);
#+end_src
These functions are used to truncate an existing file to length bytes. If the previous size of the file was greater than
length,the data beyond length is no longer accessible. Otherwise, if the previous size was less than length, the file
size will increase and the data between the old end of file and the new end of file will read as 0.
** link linkat unlink unlinkat remove
#+begin_src C
  #include <unistd.h>
  int link(const char *existingpath, const char *newpath);
  int linkat(int efd, const char *existingpath, int nfd, const char *newpath, int flag);
  int unlink(const char *pathname);
  int unlinkat(int fd, const char *pathanme, int flag);
#+end_src
#+begin_src C
  #include <stdio.h>
  int remove(const char *pathname);
#+end_src

The link and linkat create a new directory entry, newpath, that references the existing file existingpath.If the
existing file is a symbolic link, the flag argument controls whether the linkat function creates a link to the symbolic
link or to the file to which the symbolic link points. If the AT_SYMLINK_FOLLOW flag is set in the flag argument, then a
link is created to the target of the symbolic link, if the flag is clear, then a link is created to the symbolic link
itself.

If the flag argument has the AT_REMOVEDIR set, the unlinkat function can be used to remove a directory, similar to using
rmdir.
** rename renameat
#+begin_src C
  #include <stdio.h>
  int rename(const char *oldname, const char *newname);
  int renameat(int oldfd, const char *oldname, int newfd, const char *newname);
#+end_src
** symlink symlinkat
#+begin_src C
  #include <unistd.h>
  int symlink(const char *actualpath, const char *sympath);
  int symlinkat(const char *actualpath, int fd, const char *sympath);
#+end_src
A new directory entry, sympath is created that points to actualpath. It is not required that actualpath exist when the
symbolic link is created.

#+begin_src C
  #include <unistd.h>
  ssize_t readlink(const char *restrict pathname, char *restrict buf, size_t bufsize);
  ssize_t readlinkat(int fd, const char *restrict pathname, char *restrict buf, size_t bufsize);
#+end_src
Because the open function follows a symbolic link, we need a way to open the link itself and read the name in the
link.The readlink and readlinkat functions do this.
** futimens utimensat utimes
#+begin_src C
  #include <sys/stat.h>
  int futimens(int fd, const struct timespec times[2]);
  int utimensat(int fd, char *path, const struct timespec times[2], int flag);
  int utimes(const char *pathname, const struct timeval times[2]);
  struct timeval {
      time_t tv_sec;  // seconds
      long tv_usec;  // microseconds
  };
#+end_src
The futimens and utimensat functions provide nanosecond granularity for specifying timestamps, using the timespec
structure. The first element of the times array argument contains the access time, and the second element contains the
modification time. If set times to NULL, use current time instead.

The utimes function operates on a pathname. The times argument is a pointer to an array of two timestamps -- access time
and modification time, but they are expressed in seconds and microseconds
** mkdir mkdirat rmdir
#+begin_src C
  #include <sys/stat.h>
  int mkdir(const char *pathname, mode_t mode);
  int mkdirat(int fd, const char *pathname, mode_t mode);
  int rmdir(const char *pathname);
#+end_src
** Read directories
#+begin_src C
  #include <dirent.h>
  DIR *opendir(const char *pathname);
  DIR *fdopendir(int fd);
  struct dirent *readdir(DIR *dp);
  void rewinddir(DIR *dp);
  int closedir(DIR *dp);
  long teldir(DIR *dp);
  void seekdir(DIR *dp, long loc);
#+end_src
** chdir fchdir getcwd
#+begin_src C
  #include <unistd.h>
  int chdir(const char *pathname);
  int fchdir(int fd);
  char *getcwd(char *buf, size_t size);
#+end_src
First two function change current working directory to pathname or the directory fd file descriptor.

The getcwd function retrun current working dir.
