#+SETUPFILE: ~/.emacs.d/org-templates/template.org
#+PROPERTY: header-args    :results silent
#+TITLE: APUE Chapter 6 - System Data Files and Information

* Functions
** getpwuid getpwnam
#+begin_src C
  #include <pwd.h>
  // return a passwd struct through /etc/passwd file by user id
  struct passwd *getpwuid(uid_t uid);
  // return a passwd struct through /etc/passwd file by user name
  struct passwd *getpwnam(const char *name);
#+end_src

#+begin_src C :tangle getpwuid-getpwnam.c
  #include <stdio.h>
  #include <pwd.h>

  int main(void) {

      // get passwd struct by getpwuid
      struct passwd *inmove = getpwuid(1000);
      // get passwd struct by getpwnam
      // inmove = getpwnam("inmove");

      printf("username: %s\n", inmove->pw_name);
      printf("password: %s\n", inmove->pw_passwd);
      printf("userID: %d\n", inmove->pw_uid);
      printf("groupID: %d\n", inmove->pw_gid);
      printf("comment field: %s\n", inmove->pw_gecos);
      printf("initial working directory: %s\n", inmove->pw_dir);
      printf("initial shell: %s\n", inmove->pw_shell);
      return 0;
  }
#+end_src
** getpwent setpwent endpwent
#+begin_src C
  #include <pwd.h>

  // return next entry in the password file
  struct passwd *getpwent(void);

  // rewind whatever files it uses
  void setpwent(void);

  // close these files that rewinded by setpwent
  void endpwent(void);
#+end_src

#+begin_src C
  #include <stdio.h>
  #include <pwd.h>
  #include <stddef.h>
  #include <string.h>

  struct passwd *my_getpwnam(const char *);

  int main(void) {
      struct passwd *ptr = my_getpwnam("inmove");
      printf("username: %s\n", ptr->pw_name);
      return 0;
  }

  struct passwd * my_getpwnam(const char *name) {
      struct passwd *ptr;
      setpwent();
      while ((ptr = getpwent()) != NULL) {
          if (strcmp(name, ptr->pw_name) == 0)
              break;
      }
      endpwent();
      return ptr;
  }
#+end_src
** getspnam getspent setspent endspent
#+begin_src C
  #include <shadow.h>
  struct spwd *getspnam(const char *name);
  struct spwd *getspent(void);
  void setspent(void);
  void endspent(void);
#+end_src
This functions is available to access the shadow password file, similar to the set of functions used to access the
/etc/passwd file.
** getgrgid getgrnam
#+begin_src C
  #include <grp.h>
  struct group *getgrgid(gid_t gid);
  struct group *getgrnam(const char *name);
#+end_src

#+begin_src C
  #include <stdio.h>
  #include <grp.h>

  int main(void) {
      struct group *grp = getgrgid(1000);
      grp = getgrnam("root");
      printf("group name: %s\n", grp->gr_name);
      printf("encrypted password: %s\n", grp->gr_passwd);
      printf("group id: %d\n", grp->gr_gid);
      // gr_mem is an array of pointers to the user names that belong to this group
      printf("array of pointers to invididual user names: %p\n", grp->gr_mem);
      return 0;
  }
#+end_src
** getgrent setgrent endgrent
#+begin_src C
  #include <grp.h>
  struct group *getgrent(void);
  void setgrent(void);
  void endgrent(void);
#+end_src
These three functions are like their conterparts for the passrowd file.

#+begin_src C
  #include <stdio.h>
  #include <grp.h>

  int main(void) {

      setgrent();
      struct group *grp;
      while ((grp = getgrent()) != NULL) {
          printf("groupName: %s\n", grp->gr_name);
      }
      endgrent();
      return 0;
  }
#+end_src
** getgroups setgroups initgroups
#+begin_src C
  #include <unistd.h>
  // fills in the array grouplist with the supplementary group IDs.
  // Up to gidsetsize elements are stored in the array.
  // The number of supplementary group IDs stored in the array is returned by the function
  int getgroups(int gidsetsize, gid_t grouplist[]);
  #include <grp.h>
  #include <unistd.h>
  // can be called by the superuser to set the supplementary group ID list for the calling process
  // list: contains the array of group IDs
  // ngroups: specifies the number of elements in the array. Cannot be larger than NGROUPS_MAX
  // *setgroups* is usually called from the *initgroups*
  int setgroups(size_t size, const gid_t *list);
  #include <grp.h>
  #include <unistd.h>
  // reads the entire group file with the functions *getgrent* *setgrent* *endgrent* and determines the group membership fro username. Then calls *setgroups* to initialize the supplymentary group ID list for the user
  // basegid is the group ID from the password file for username
  int initgroups(const char *username, gid_t basegid);
#+end_src
** uname
#+begin_src C
  #include <sys/utsname.h>
  int uname(struct utsname *name);

  struct utsname {
      char sysname[]; // name of the operating system
      char nodename[]; // name of this node
      char release[]; // current release of operating system
      char version[]; // current version of this release
      char machine[]; // name of hardware type
  };
#+end_src
This function will fill in the name parameter
#+begin_src C
  #include <stdio.h>
  #include <sys/utsname.h>

  int main(void) {
      struct utsname name;
      uname(&name);
      printf("sysname: %s\n", name.sysname);
      printf("nodename: %s\n", name.nodename);
      printf("release: %s\n", name.release);
      printf("version: %s\n", name.version);
      printf("machine: %s\n", name.machine);
      return 0;
  }
#+end_src
** gethostname
#+begin_src C
  #include <unistd.h>
  int gethostname(char *name, size_t namelen);
#+end_src
#+begin_src C
  #include <stdio.h>
  #include <unistd.h>
  #include <stdlib.h>

  int main(void) {
      char *name = malloc(sizeof(char) * 128);
      gethostname(name, 128);
      printf("hostname: %s", name);
      return 0;
  }
#+end_src
** time
#+begin_src C
  #include <time.h>
  time_t time(time_t *calptr);
#+end_src
Current time is returned as the value of the function. If the calptr is not NULL, the time value is also stored at the
location pointed to by calptr.
#+begin_src C
  #include <stdio.h>
  #include <time.h>

  int main(void) {
      time_t current_time = time(NULL);
      printf("%lu\n", current_time); // timestamp
      printf("%s\n", ctime(&current_time));
      return 0;
  }
#+end_src
** clock_gettime
#+begin_src C
  #include <sys/time.h>
  #include <time.h>
  int clock_gettime(clockid_t clock_id, struct timespec *tsp);
#+end_src
A clock is identified by the clockid_type, Standard values are:
| Identifier               | Option                 | Description                             |
|--------------------------+------------------------+-----------------------------------------|
| CLOCK_REALTIME           |                        | real system time                        |
| CLOCK_MONOTONIC          | _POSIX_MONOTONIC_CLOCK | real system time with no negative jumps |
| CLOCK_PROCESS_CPUTIME_ID | _POSIX_CPUTIME         | CPU time for calling process            |
| CLOCK_THREAD_CPUTIME_ID  | _POSIX_THREAD_CPUTIME  | CPU time for calling thread             |
#+begin_src C
  #include <stdio.h>
  #include <time.h>
  #include <unistd.h>

  int main(void) {
      struct timespec tsp;
      int i = 0;
      while(i++ < 9999999);
      int gettime_return = clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &tsp);
      printf("process cputime: %d, %lu\n", gettime_return, tsp.tv_sec);
      return 0;
  }
#+end_src
** clock_getres
#+begin_src C
  #include <time.h>
  int clock_getres(clockid_t clock_id, struct timespec *tsp);
#+end_src
** clock_settime
#+begin_src C
  #include <time.h>
  int clock_settime(clockid_t clock_id, const struct timespec *tsp);
#+end_src
** gettimeofday
#+begin_src C
  #include <time.h>
  int gettimeofday(struct timeval *restrict tp, void *restrict tzp);
#+end_src
The only legal value for tzp is NULL.
** gmtime localtime
#+begin_src C
  #include <time.h>
  struct tm *gmtime(const time_t *calptr);
  struct tm *localtime(const time_t *calptr);

  struct tm {
      // The reason that the seconds can be greater than 59 is to allow for a leap second
      int tm_sec; // seconds after the minute [0-60]
      int tm_min; // minutes after the hour [0-59]
      int tm_hour; // hours after midnight: [0-23]
      int tm_mday; // day of the month: [1-31]
      int tm_mon; // monthes since January: [0-11]
      int tm_year; // year - 1900
      int tm_wday; // days since Sunday [0-6]
      int tm_yday; // days since January [0-365]
      int tm_isdst; // daylight saving time flags: <0,0,>0
  };
#+end_src
#+begin_src C
  #include <stdio.h>
  #include <time.h>

  int main(void) {
      time_t now = time(NULL);
      struct tm *ng = gmtime(&now);
      printf("now is: %d, %d, %d\n", (ng->tm_year + 1900), (ng->tm_mon + 1), (ng->tm_yday + 1));
      ng = localtime(&now);
      printf("now is: %d, %d, %d\n", (ng->tm_year + 1900), (ng->tm_mon + 1), (ng->tm_yday + 1));
      return 0;
  }
#+end_src
** mktime
#+begin_src C
  #include <time.h>
  time_t mktime(struct tm *tmptr);
#+end_src
#+begin_src C
  #include <stdio.h>
  #include <time.h>

  int main(void) {
      time_t now = time(NULL);
      struct tm *ng = localtime(&now);

      time_t mktime_now = mktime(ng);

      printf("now: %d, mktime_now: %d\n", now, mktime_now);

      return 0;
  }
#+end_src
** strftime strftime_l
#+begin_src C
  #include <time.h>
  size_t strftime(char *restrict buf, size_t maxsize, const char *restrict format,
                  const struct tm *restrict tmptr);
  size_t strftime_l(char *restrict buf, size_t maxsize, const char *restrict format,
                    const struct tm *restrict tmptr, locale_t local);
#+end_src
The *strftime_l* function allows the caller to specify the local as an argument. The *strftime* function uses the local
specified by the TZ environment variable.
#+begin_src C
  #include <stdio.h>
  #include <time.h>
  #include <stdlib.h>

  int main(void) {
      time_t now = time(NULL);
      struct tm *tm_now = localtime(&now);
      char *buf = malloc(sizeof(char) * 128);
      strftime(buf, 128, "%Y-%m-%d %t %H:%M:%S %Z", tm_now);
      printf("buf: %s", buf);
      return 0;
  }
#+end_src
| Format | Description                        |                  Example |
|--------+------------------------------------+--------------------------|
| %a     | abbreviated weekday name           |                      Thu |
| %A     | full weekday name                  |                 Thursday |
| %b     | abbreviated month name             |                      Jan |
| %B     | full month name                    |                  January |
| %c     | date and time                      | Thu Jav 19 21:24:52 2012 |
| %d     | day of month                       |                       19 |
| %D     | date[MM/DD/YY]                     |                 01/19/12 |
| %H     | hour of the day 24-hour format     |                       21 |
| %I     | hour of the day 12-hour format     |                        9 |
| %j     | day of the year                    |                      019 |
| %m     | month                              |                    01-12 |
| %M     | minute 00-59                       |                       12 |
| %n     | newline character                  |                          |
| %p     | AM/PM                              |                          |
| %r     | locale's time 12-hour format       |              09:24:52 PM |
| %R     | same as %H:%M                      |                    21:24 |
| %S     | second 00-60                       |                          |
| %t     | horizontal tab character           |                          |
| %T     | same as %H:%M:%S                   |                          |
| %u     | weekday Monday = 1, 1-7            |                          |
| %w     | weekday Sunady = 0, 0-6            |                          |
| %x     | locale's date                      |                 01/19/12 |
| %X     | locale's time                      |                 21:24:52 |
| %y     | last two digits of year            |                       12 |
| %Y     | year                               |                     2012 |
| %z     | offset from UTC in ISO 8601 format |                    -0500 |
| %Z     | time zone name                     |                      EST |
** strptime
#+begin_src C
  #include <time.h>
  char *strptime(const char *restrict buf, const char *restrict format, struct tm *restrict tmptr);
#+end_src
#+begin_src C
  #include <stdio.h>
  #define __USE_XOPEN
  #include <time.h>
  #include <stdlib.h>

  int main(void) {
      char *buf = "2020-01-01";
      struct tm tm_date;
      char *format = "%Y-%m-%d";
      strptime(buf, format, &tm_date);
      printf("date is: %d, %d, %d\n", (tm_date.tm_year + 1900), (tm_date.tm_mon + 1), (tm_date.tm_yday + 1));
      return 0;
  }
#+end_src
