#+SETUPFILE: ~/.emacs.d/org-templates/template.org
#+TITLE: 标签

* 标签的作用
#+begin_verse
对于一些相互关联又在不同文件的笔记,我们可以给它打上相同的标签,这样就可以通过某种方式(Agenda)来进行访问
标签被放置在提纲的同一行,以':'作为开始和结束. 如 ':work:urgent:'
#+end_verse

* 标签的外观
#+begin_src emacs-lisp :results none
  (setq org-tag-faces
        '(("work" . "red")
          ("home" . "green")
          ("study" . "yellow")))
#+end_src

* 标签的继承
#+begin_verse
子提纲继承父提纲的所有标签
使用 #+FILETAGS 来设置文件所有提纲都继承的标签
这样有一个不好的地方就是,当我们使用agenda在标签中搜索的时候.如果父提纲有某个标签,所有子提纲都会被搜索出来
这样就会显得特别多.
通过把 =org-use-tag-inheritance= 设置为nil,全局标签的继承性
也可以设置 =org-tags-exclude-from-inheritance= 来关闭部分标签的继承性(经测试,好像不起作用,有待进一步测试)
#+end_verse
#+begin_verse
(setq org-use-tag-inheritance nil)
(setq org-tags-exclude-from-inheritance '("study"))
#+end_verse
#+begin_src org :results none
  ,#+FILETAGS: :study:
#+end_src

* 设置备选标签                                                        :@home:
#+begin_verse
当我们为提纲设置标签的时候,emacs会为我们提供一组可选标签的组合,当然也可以自行输入标签
默认情况下,会以已经存在的标签来做为备选方案.设置变量 =org-tag-alist= 来设置全局备选标签
如果备选标签设置了快捷访问,那么是无法随意输入新的标签的
#+end_verse
#+begin_src emacs-lisp :results none
  (setq org-tag-alist
        '(("@work" . ?w)
          ("@home" . ?h)
          ("@study" . ?s)))

  (setq org-tag-alist
        '(("@work" . nil)
          ("@home" . nil)
          ("@study" . nil)))
#+end_src

#+begin_verse
要为某个文件设置备选标签,使用 #+TAGS
#+end_verse
#+begin_src org :results none
  ,#+TAGS: @work(w) @home(h) @tennisclub(t)
#+end_src

#+begin_verse
如果要在某个文件中禁用全局备选标签,只要把 #+TAGS 设置为什么都没有
#+end_verse
#+begin_src org :results none
  ,#+TAGS:
#+end_src

#+begin_verse
通过#+TAGS设置的备选标签会把通过 =org-tag-alist= 设置的备选标签冲掉.
如果既想要有全局的备选标签,又想要为某个文件设置独特的备选标签,就用 =org-tag-persistent-alist=
如果想要掉 =org-tag-persistent-alist=, 则设置 =#+STARTUP: noptag=
#+end_verse

* 标签分组
#+begin_verse
对于同一组的标签,它们是互斥的关系.
#+end_verse
#+begin_src emacs-lisp :results none
  (setq org-tag-alist
        '((:startgroup . nil)
          ("@work" . ?w)
          ("@home" . ?h)
          ("@tennisclub" . ?t)
          (:endgroup . nil)
          ("laptop" . ?l)
          ("pc" . ?p)))
#+end_src

#+begin_verse
在单个文件中用 '{}' 来对标签分级.注意, 标签名一定要与 '{}' 用空格分开
#+end_verse
#+begin_src org :results none
  ,#+TAGS: { @work(w) @home(h) @tennisclub(t) } laptop(l) pc(p)
#+end_src

* 标签的层次结构
#+begin_verse
我们可以定义标签的时候把标签括起来, ':'前面部分表示标签名,后面部分表示所有成员
如下例所示,其中 GTD 被叫作 *组名* Control,Persp 被叫作 *成员*
当我们通过 GTD 来搜索的时候,所有被标记为 Control Persp 的提纲都会被搜出来
#+end_verse
#+begin_src org :results none
  ,#+TAGS: [ GTD : Control Persp ]
#+end_src
#+begin_verse
如下则成员之间互斥
#+end_verse
#+begin_src org :results none
  ,#+TAGS: { Context : @Home @Work @Call }
#+end_src

#+begin_verse
成员也可以是另外一个组.如下所示
用 startgroup,endgroup 代替 startgrouptag,endgrouptag 成员之间就成为互斥关系
#+end_verse
#+begin_src emacs-lisp :results none
  (setq org-tag-alist
        '((:startgrouptag)
          ("GTD")
          (:grouptags)
          ("Control")
          ("Persp")
          (:endgrouptag)
          (:startgrouptag)
          ("Control")
          (:grouptags)
          ("Context")
          ("Task")
          (:endgrouptag)))
#+end_src

#+begin_verse
成员还可以用正则表达式来表示
#+end_verse
#+begin_src org :results none
  ,#+TAGS: [ Vision : {V@.+} ]
#+end_src

#+begin_verse
函数 =org-toggle-tags-groups= 用于暂忽略组标签,被绑定在 =C-c C-x q=
设置 =org-group-tags= 为nil,则全局忽略组标签
#+end_verse

* 快捷键
1. C-c C-q (org-set-tags-command): 对当前提纲设置标签


* test1                                                          :home:study:

* test2
#+begin_example
  ,#+TAGS: [ GTD : Control Persp ]
#+end_example
** test2                                                           :Control:
** test3                                                             :Persp:
