#+SETUPFILE: ~/.emacs.d/org-templates/template.org
#+PROPERTY: header-args    :results silent
#+TITLE: Org Mode - Working with Source Code

* Chapter 15 - Working with Source Code
** Structure of Code Blocks
#+begin_example
#+name: <name>
#+begin_src <language> <switches> <header-arguments>
<body>
#+end_src
#+end_example
#+begin_verse
1. name: *Optional*. Names the source block so it can be called.
2. language: *Mandatory*. It is the identifier of the source code language in the block.
3. switches: *Optional*. Switches provide finer control of the code execution, export and format.
4. header arguments: *Optional*. Heading arguments control many aspects of evaluation, export and tangling of code blocks.
5. body: Source code in the dialect of the specified language identifier.
#+end_verse
** Set Header Arguments
*** System-wide header arguments
The System-wide values of header arguments can be specified by customizing the *org-babel-default-header-args* variable, which defaults to the following values:
#+begin_variable
1. :session => "none"
2. :results => "replace"
3. :exports => "code"
4. :cache => "no"
5. :noweb => "no"
#+end_variable
The Example below sets ':noweb' header arguments to 'yes', which makes org expand ':noweb' reference by default
#+begin_src emacs-lisp
  (setq org-babel-default-header-args
        (cons '(:noweb . "yes")
              (assq-delete-all :noweb org-babel-default-header-args)))
#+end_src
Each language can have separate default header arguments by customizing the variable *org-babel-default-header-args:<LANG>*.
*** Header arguments in Org mode properties
For header arguments applicable to the buffer, use 'PROPERTY' keyword anywhere in the Org file.
1. =#+PROPERTY: header-args:python :session *P*=: Only influence the python source block.
2. =#+PROPERTY: header-args :results silent=: Influence all the source block.
*** Header arguments in drawers
This header arguments apply at the sub-tree level on down.
#+begin_src org
  ,* Heading
    :PROPERTIES:
    :header-args: :session *session-1*
    :header-args:R: :session *R-session-1*
    :END:
#+end_src
*** Code block specific header arguments
Header arguments are most commonly set at the source code block level, on the '#+begin_src' line.
#+begin_src org
  ,#+begin_src python :results silent :exports code :var n=0
  ,#+end_src

  ,#+header: :var data1=1
  ,#+header: :var data2=2
  ,#+begin_src python
  return (data1, data2)
  ,#+end_src
#+end_src
*** Header arguments in function calls
Here are two CALL expressions.
The First one =:session special= applied to the evaluation of the 'factorial' code block.
Second one =:exports results= applied to the evaluation of the 'CALL' line

#+begin_src org
  ,#+name: factorial
  ,#+begin_src python :var n=10
    return n + 10;
  ,#+end_src
  ,#+CALL: factorial[:session special](n=5)
  ,#+CALL: factorial(n=20) :exports results
#+end_src
** Environment of a Code Block - the :var header argument   :HeaderArgument:
The :var argument declaring a variable and assigning a default value, syntax as follow:

:var NAME=ASSIGN

For example
#+begin_src org
  ,#+begin_src python :var name="inmove" age=18
    return "My name is {}, {} years old".format(name, age)
  ,#+end_src
#+end_src

The ASSIGN can be string, number, name of a code block or the result of a code block or a table.

** Table as the ASSIGN value - :rownames :colnames          :HeaderArgument:
For example: the return value is 2, because the header of the table is removed before execute the code block.

The header argument *colnames* has three values, 'yes', 'no', 'nil'.
1. nil: default. If an table has column names -- because the second row is a horizontal rule, Then Org removes the column names, processes the table, puts back the column names and then writes the table to the results block.
2. yes: Org does the same to the first row, even if the initial table does not contain any horizontal rule.
3. no: Org does not pre-process column names at all.

Similary, the *rownames* can take two values, 'yes' or 'no'
1. no: default, do not pre-process the first column.
2. yes: when set to yes, Org removes the first column, processes the table, puts back the first column, and then writes the table to the results block.
#+begin_src org
  ,#+name: test-table
  | a | b |
  |---+---|
  | 1 | 2 |
  | 3 | 4 |

  ,#+begin_src python :var table=test-table :results value
    return len(table)
  ,#+end_src

  ,#+RESULTS:
  : 2
#+end_src
** Sessions - :session                                      :HeaderArgument:
Only languages that provide interactive evaluation can have session support, not useful for me now.
** Working directory - :dir                                 :HeaderArgument:
The *:dir* header argument specifies the default directory during code block execution.
Dir can be specified to a remote machine.
#+begin_src org
  ,#+begin_src shell :results value :dir /ssh:inmove@inmove.com.cn:/home/inmove/code
    ls -alh
  ,#+end_src

  ,#+RESULTS:
  | total       | 56K |        |        |      |     |    |       |                      |
  | drwx------. |  30 | inmove | inmove | 4.0K | Dec | 10 | 17:31 | ..                   |
  | drwxrwxr-x. |   7 | inmove | inmove | 4.0K | Oct | 22 | 14:09 | blog                 |
  | drwxrwxr-x. |   3 | inmove | inmove | 23   | Dec | 10 | 17:40 | c                    |
#+end_src
** Execute code block
*** Limit code block evaluation - :eval                    :HeaderArgument:
The :eval header argument can limit evaluation of specific code blocks.The *org-confirm-babel-evaluate* variable holds the global setting.

1. never or no: Never evaluate the source code.
2. query: Org promopts the user for permission to evaluate the source code.
3. never-export or no-export: Org does not evaluate the source code when exporting, yet the user can evaluate it interactively.
4. query-export: Org prompts the user for permission to evaluate the source code during export.
*** Cache value of code block - :cache                     :HeaderArgument:
If evaluate a code block may take a long time and the value may not always change, use :cache to cache it.

1. no: default value
2. yes: cache value
** Results of Evaluation                                    :HeaderArgument:
There are four classes of options.
*** Collection
1. value: Default. The return value of the last statement in the code block will be the return value of the code block.
   #+begin_src org
     ,#+begin_src python :results value
       return 10;
     ,#+end_src

     ,#+RESULTS:
     : 10
   #+end_src
2. output: The standard output will be the return value of the code block
   #+begin_src org
     ,#+begin_src python :results output
       print(10)
     ,#+end_src

     ,#+RESULTS:
     : 10
   #+end_src
*** Type
1. table or vector
   #+begin_src org
     ,#+name: table0
     | a | b | c | d | e |
     |---+---+---+---+---|
     | 1 | 2 | 3 | 4 | 5 |
     |---+---+---+---+---|
     | 1 | 2 | 3 | 4 | 5 |
     |---+---+---+---+---|
     | 1 | 2 | 3 | 4 | 5 |

     ,#+begin_src python :results table :hlines no :var table=table0
       return table
     ,#+end_src

     ,#+RESULTS:
     | a | b | c | d | e |
     | 1 | 2 | 3 | 4 | 5 |
     | 1 | 2 | 3 | 4 | 5 |
     | 1 | 2 | 3 | 4 | 5 |

     ,#+begin_src python :results table :var table=table0 :hlines yes
       return table
     ,#+end_src

     ,#+RESULTS:
     | a | b | c | d | e |
     |---+---+---+---+---|
     | 1 | 2 | 3 | 4 | 5 |
     |---+---+---+---+---|
     | 1 | 2 | 3 | 4 | 5 |
     |---+---+---+---+---|
     | 1 | 2 | 3 | 4 | 5 |
   #+end_src
2. list
   #+begin_src org
     ,#+name: table1
     | a | b | c | d | e |
     |---+---+---+---+---|
     | 1 | 2 | 3 | 4 | 5 |

     ,#+begin_src python :results list :var table=table1
       return table
     ,#+end_src

     ,#+RESULTS:
     - (1 2 3 4 5)

   #+end_src
3. scalar or verbatim
   #+begin_src org
     ,#+name: table2
     | a | b | c | d | e |
     |---+---+---+---+---|
     | 1 | 2 | 3 | 4 | 5 |

     ,#+begin_src python :results scalar :var table=table2
       return table
     ,#+end_src

     ,#+RESULTS:
     : [[1, 2, 3, 4, 5]]
   #+end_src
4. file: save the results of execution of the code block to that file, then insert a link to it.
   1. The *output-dir* header arguments indicate the location of the file.
   2. The *file-ext* header arguments indicate the extension of the file.
   3. The *file-desc* header arguments indicate the link's description.
   4. The *sep* header arguments indicate the separator when save a table to the file.
   #+begin_src org
     ,#+name: table3
     | a | b | c |
     |---+---+---|
     | 1 | 2 | 3 |
     | 4 | 5 | 6 |

     ,#+begin_src python :results file :file test.txt :var table=table3
       return table
     ,#+end_src

     ,#+RESULTS:
     [[file:test.txt]]
   #+end_src
*** Format
1. code: Result enclosed in a code block, for example:
   #+begin_verse
   The *wrap* header argument unconditionally marks the results block by appending string to "#+BEGIN_" and "#+END_".
   For example =:wrap json json=
   The first 'json' becomes '#+begin_json' and '#+begin_json'.
   The senond 'json' is the a language specific.
   Both 'json' can be omit, the results will wrapped with '#+begin_results' and '#+end_results'
   #+end_verse
   #+begin_src org
     ,#+begin_src python :results code :wrap json
       return 10
     ,#+end_src

     ,#+RESULTS:
     ,#+begin_json
     10
     ,#+end_json
   #+end_src
2. drawer: Result wrappend in a 'RESULTS' drawer
   #+begin_src org
     ,#+begin_src python :results drawer
       return 10
     ,#+end_src

     ,#+RESULTS:
     :results:
     10
     :end:
   #+end_src
3. html: Results enclosed in a 'BEGIN_EXPORT html' block
4. latex: Results enclosed in a 'BEGIN_EXPORT latex' block
5. link or graphics: Result is a link to the file specified in ':file' header argument, nothing is written to the disk.
   #+begin_src org
     ,#+begin_src python :results link :file "download.tar.gz"
       return 10
     ,#+end_src

     ,#+RESULTS:
     : 10
   #+end_src
6. org: Results enclosed in a "BEGIN_SRC org" block
7. pp: Result converted to pretty-print source code.
   #+begin_src org
     ,#+begin_src python :results pp
       return {"name": 'inmove'}
     ,#+end_src

     ,#+RESULTS:
     : {'name': 'inmove'}
   #+end_src
8. raw: Interpreted as raw Org mode. Inserted directly into the buffer.
   #+begin_src org
     ,#+begin_src python :results raw
       return {"chain": {"map": "doc"}}
     ,#+end_src

     ,#+RESULTS:
     {'chain': {'map': 'doc'}}
   #+end_src
*** Handling
1. silent: Do not insert results in the Org mode buffer, but echo them in the minibuffer.
2. replace: Default, insert results in the Org buffer, remove previous ones.
3. append: Append results to the Org buffer.
4. prepend: Prepend results to the Org buffer.
** Post processing - :post                                  :HeaderArgument:
The *post* header argument is for post-processing. When 'post' has any value, Org binds the results to **this** variable for easy passing to 'var' header argument specifications.
#+begin_src org
  ,#+name: show-name
  ,#+begin_src python :var name='inmove'
    return "my name is {}".format(name)
  ,#+end_src

  ,#+begin_src python :post show-name(name=*this*)
    return 'mei'
  ,#+end_src

  ,#+RESULTS:
  : my name is mei
#+end_src
** Exporting Code Blocks - :exports                         :HeaderArgument:
The *exports* header argument is to specify if that part of the Org file is exported to when export the org file to html or pdf or other files.
*Exports* value can be 'code' 'results', 'both' or 'none'

#+begin_src org
  ,#+begin_src python :results value :exports code :file test.py
    return True
  ,#+end_src

  ,#+RESULTS:
  : True
#+end_src
** Extracting Source Code - :tangle                         :HeaderArgument:
The *tangle* header argument is for extract source code from code block
1. 'yes': Extract the code block to source file, the name of the source file is derived from the name of the Org file.
2. 'no': Do not export the code block to source code..
3. filename: Extract the code block to source file named filename.

The *mkdirp* header argument creates parent directories for tangled files if the directory does not exist. It's values is 'yes' or 'no'.

The *comments* header argument controls inserting comments into tangled files.
1. 'no': no comments
2. 'link': A link back to the Org file
3. 'yes': Kept for backward compatibility, same as 'link'
4. 'org': Nearest headline text from Org file is inserted as comment.
5. 'both': Includes both 'link' and 'org' options.
6. 'noweb': Includes 'link' option, expands Noweb references, and wraps them in link comments inside the body of the code block.

The *padline* header argument controls insertion of newlines to pad source code in the tangled file.
1. 'yes': Default, insert a newline before and after each code block in the tangled file.
2. 'no': No not insert newlines to pad the tangled code blocks.

The *shebang* header argument can results into executable script files.

The *tangle-mode* header argument specifies what permissions to set for tangled files by set-file-modes, for example, to make a read-only tangled file, use ':tangle-mode (identity #o444)'
** Enable or Disable Evaluation of Code Block for specific language
#+begin_src org
  ,#+begin_src emacs-lisp
    (org-babel-do-load-languages
      'org-babel-load-languages
      '((emacs-lisp . nil)
        (ditta . t))
    )
  ,#+end_src
#+end_src
** Noweb Reference Syntax - :noweb                          :HeaderArgument:
The Noweb Reference Syntax is =<<CODE-BLOCK-ID>>=
The *noweb* header argument controls expansion of Noweb syntax references. Expansions occur when source code blocks are evaluated, tangled, or exported.
1. 'no': Default, No expansion of Noweb syntax references when *evaluating* *tangling* or *exporting*.
2. 'yes': Expansion of Noweb syntax references when *evaluating* *tangling* or *exporting*.
3. 'tangle': Expansion just for *tangling*.
4. 'no-export: Expansion for *evaluating* or *tangling*, no expansion for *exporting*.
5. 'strip-export': Expansion for *evaluating* or *tangling*, remove Noweb syntax references when *exporting*.
6. 'eval': Expansion of Noweb syntax references in the body of the code block only before *evaluating*.

#+begin_src org
  ,#+name: name
  ,#+begin_src python
    name = "inmove"
  ,#+end_src
  ,#+begin_src python :noweb yes :tangle yes
    <<name>>
    print(name)
  ,#+end_src
#+end_src
