#+SETUPFILE: ~/.emacs.d/org-templates/level-0.org
#+TITLE: Dates and Times

* Org Mode 的日期格式
** 普通格式
<2020-10-27 Tue>
** TODO 重复执行的工作
:PROPERTIES:
:LAST_REPEAT: [2020-10-27 Tue 22:44]
:END:
- State "DONE"       from "TODO"       [2020-10-27 Tue 22:44]
- State "DONE"       from "TODO"       [2020-10-27 Tue 22:44]
<2020-12-01 Tue +1w>
#+begin_verse
其中w代表周,其它还有d(每天),m(每月),y(每年),h(每小时)
当我们把这个条目从TODO变成DONE的时候,会在条目的下面增加一条最近完成的时间戳,但是条目本身依然是TODO状态
并且条目下面会多一个PROPERTY,key为LAST_REPEAT,值为当前时间
#+end_verse
** 时间序列
<2020-10-27 Tue>--<2020-11-03 Tue>
#+begin_verse
当我们把光标放在'>'然后使用 =C-c .= 的来创建一个时间戳的时候,新的时间戳会和前面的时间戳组成一个时间序列,中间以'--'连接
并且在agenda view中以(n/m)来进行表示.其中m表示两个时间戳之间的天数.n表示当前处于第几天.比如,时间序列在10.27~11.03,当前时间为10.31,那么m为8,n为5
#+end_verse
** 不活动的时间戳
[2020-10-27 Tue]
#+begin_verse
不活动的时间戳将不会在agenda view出现
#+end_verse
** 日记形式的表现形式
<%%(diary-float t 4 5)> : 每个月的第5个周四

* 快捷键
1. C-c . (org-time-stamp): 在当前光标处创建一个时间戳.
   <2020-10-27 Tue>
   1. 如果当前没有时间戳,则在当前光标处新增一个时间戳
   2. 如果光标在一个时间戳内部(<>,包括<>之间),则更新这个时间戳
   3. 如果光标在时间戳的'>'后一个字符,则添加一个时间戳,与前面一个时间戳组成时间序列
   4. C-u C-c .: 把小时,分钟也一并显示在时间戳里
   5. C-u C-u C-c .: 把当前时间戳插入到光标所在位置,同时带上小时和分钟
2. C-c ! (org-time-stamp-inactive): 和 =C-c .= 一样,只不过插入的是inactive状态的时间
   <2020-10-26 Mon>
3. C-c C-c: 当光标处在一个时间上面的时候,修正这个时间戳.有可能星期和日期对不上,或者不小心改到了时间的内容,使用 =C-c C-c= 进行修正
4. C-c < (org-date-from-calendar): 直接插入当前的日期
5. C-c > (org-goto-calendar): 进入到calendar buffer
6. C-c C-o (org-open-at-point): 当我们在一个时间戳上面使用这个命令的时候,会在另一个buffer中显示所有带有这个日期的条目列表.当然只显示活动的条目
7. S-LEFT/RIGHT (org-timestamp-down/up-day): LEFT,把时间戳往前一天.RIGHT,往后一天
8. S-UP/DOWN (org-timestamp-up/own): 当光标在year上则修改year,在month上则修改month,以此类推
   1. 当我们修改minutes *org-time-stamp-rounding-minutes* 的第二个值决定了时间修改的间隔.其默认值为(0,5).5表示以5分钟为间隔
   2. 当光标在<>或者[]之上的时候,使用S-UP/DOWN,则可以在ACTIVE和INACTIVE之间切换
   3. 当光标在某个item上面的时候,item表示年,月,日,分钟,小时
      1. 如果时间戳的小时:分钟是一个时间段,那么修改第一个时间,同步会修改第二个时间,以保持时间段不变.但是修改第二个的时候,第一个不会同步更改
      <2020-10-29 Thu 06:10-12:40>
9. C-c C-y (org-evaluate-time-range): 如果光标处于一个time range之间,则计算出时间差.加上C-u前缀则会记录到行的最后
   <2020-10-27 Tue 23:34>--<2020-10-30 Fri 23:39> 3d 00:05
* 可输入的时间与日期的格式
#+begin_verse
当我们使用 =C-c .= 这个命令的时候,我们会进入到 /Calendar Buffer/ 中.在这里面我们可以选择日期,也可以自己输入一个日期,用Enter确认后,这个时间戳就会保存在当前光标处
我们可以输入的格式有很多种.其中需要注意的一个地方就是,如果我们只输入一部分,那么其它部分Emacs将怎么处理呢.
这里有个 /default date and time/ 的东西.一般情况下为当前时间.但是,如果我们本身在一个时间戳的内部进入到 /Calendar Buffer/ 的时候,这个默认值就是光标所处的这个时间戳了
当我们输入一个未来的日期的时候呢,在 /Calendar Buffer/ 中我们会看到 =(=>F)= 的字样.比如我们不输入当前年份的时候,最终得到的时间戳的年份则是下一年.
以下是Emacs识别的一些格式,当前时间为 <2020-10-27 Tue 23:58>

注: -,+,--,++表示相对时间.-,+一定是以当前时间做为时间基数.--,++则是以 /default date and time/ 作为时间基数

1. 3-2-5(年-月-日) => <2003-02-05 Wed>
2. 2/5/3(月-日-年) => <2003-02-05 Wed>
3. 14(比当前日要早的某一天) => <2020-11-14 Sat>
5. 28(比当前日要晚的某一天) => <2020-10-28 Wed>
6. 2/5(月/日) => <2021-02-05 Fri>
7. Fri(下一个周五) => <2020-10-30 Fri>
8. sep 15(不输入年,月 日 比当前时间要早) => <2021-09-15 Wed>
9. dec 15(不输入年,月 日 比当前时间要晚) => <2020-12-15 Tue>
10. sep 12 9 (月 日 年) => <2009-09-12 Sat>
11. 12:45 =><2020-10-28 Wed 12:45>
12. 22 sep 0:34 (pdf上面是 22 sept 0:34 但是出来的结果好像不对,9月应该是sep) => <2021-09-22 Wed 00:34>
13. w4 (今年第4周的周一) => <2020-01-20 Mon>
14. 2020 w4 fri (2020年第4周的周五) => <2020-01-24 Fri>
15. 2020-w04-5 (同上) => <2020-01-24 Fri>
16. +0 => today
17. . => today
18. +4d (4天后) => <2020-11-01 Sun>
19. +4 (同上)
20. +2w (2周后) => <2020-11-11 Wed>
21. ++5 => 5天后
22. +2tue (从现在开始算的第二个周二) => <2020-11-10 Tue>
23. 11am-1:15pm => <2020-10-28 Wed 11:00-13:15>
24. 11am--1:15pm (同上)
25. 11am+2:15 (同上)
#+end_verse

* Calendar Buffer 中的快捷键
#+begin_verse
1. S-RIGHT: 接下来的一天
2. S-LEFT: 以前的一天
3. S-DOWN: 接下来的一周的今天
4. S-UP: 以前的一再的今天
5. M-S-RIGHT: 接下来的一个月
6. M-S-LEFT: 以前的一个月
7. >: 日历往后scroll一个月
8. <: 日历往前scroll一个月
9. M-v: 日历往后scroll3个月
10. C-v: 日历往前scroll3个月
#+end_verse

* 截止日期与日期安排
** DEADLINE
DEADLINE: <2020-10-31 Sat -4d>
#+begin_verse
预计将在这个时间点完成这项工作.
在agenda view中,截止日期以橘色显示.当前日期下面会有距离截止日期的天数.
如果在提醒范围内则会以黄色显示
提醒范围以变量 *org-deadline-warning-days* 来设置.
比如,如果我设置 *org-deadline-warning-days* 为5,当前时间为<2020-10-28 Wed>截止日期为<2020-11-01 Sun>
=(setq org-deadline-warning-days 5)= 那么在agenda view中将看到
黄色的高亮显示的 "dates-and-times:In   4 d.:  DEADLINE"
和橘色的高亮显示 "dates-and-times:Deadline:   DEADLINE"
pdf上面说用 -nd 来表示如:<2020-11-01 Sun -5d> 但是我试了一下好像和预想的有点不一样,暂先不用这表示吧
#+end_verse
** SCHEDULED
SCHEDULED: <2020-10-25 Fri>
预计将在这个时间点开始这项工作
#+begin_verse
对于在将来的某个时间开始做的工作,在agenda view中将以 /绿色/ 高亮显示
如果SCHEDULED时间是在以前的某个时间,在agenda view中将以 /蓝色/ 高亮显示
当我们在后面加上 -2d 的时候,虽然预计在25号开始工作,但是agenda view中只有到了27号才会显示
#+end_verse
** 快捷键
#+begin_verse
1. C-c C-d (org-deadline): 插入预计的截止日期
2. C-c C-s (org-schedule): 插入预计的开始日期
3. C-c / d (org-check-deadlines): 创建一个sparse tree,显示所有已经逾期的deadlines
4. C-c / b (org-check-before-date): 创建一个sparse tree,显示所有deadlines/scheduled items before a given date.
5. C-c / a (org-check-after-date): 创建一个sparse tree,显示所有deadlines/scheduled items after a given date.
#+end_verse
