#+SETUPFILE: ~/.emacs.d/org-templates/template.org
#+TITLE: Unix高级环境编程


* 文件IO
** 文件描述符
#+begin_verse
与文件IO相关的操作都是基于文件描述符.文件描述符由 /open/ 或 /creat/ 函数返回
文件描述符由从0开始的正整数开始构成.上限值为 OPEN_MAX - 1
其中0表示标准输入,1表示标准输出,2表示标准错误输出.
由三个常量 /STDIN_FILENO/ /STDOUT_FILENO/ /STDERR_FILENO/ 来表示.它们被定义在 *unistd.h* 中
#+end_verse
** 相关的函数
*** open 与 openat
#+begin_verse
函数原型:
#+end_verse
#+begin_src c
  #include <fcntl.h>
  int open(const char *path, int oflag, ... /* mode_t mode */);
  int openat(int fd, const char *path, int oflag, ... /* mode_t mode */);
#+end_src
#+begin_verse
1. path: 文件的目录,可以是相对路径,也可以是绝对路径
2. oflag: 1~5属于互斥类型的flag <<<fd-flags>>>
   1. O_RDONLY: 只读打开
   2. O_WRONLY: 只写打开
   3. O_RDWR: 读写打开
   4. O_EXEC: 执行打开
   5. O_SEARCH: 查找打开,只有打开目录时有效
   6. O_APPEND
   7. O_CLOEXEC
   8. O_CREAT: 如果文件不存在,那么创建它.此flag要求必须要传mode参数
   9. O_DIRECTORY: 如果path不是目录,直接返回出错
   10. O_EXCL: 与 O_CREAT 一起使用.如果文件已经存在,返回出错
   11. O_NOCTTY: 如果path是一个终端设备,不要把此终端分配为这个进程的控制终端
   12. O_NOFOLLOW: 如果path是一个符号链接,返回出错
   13. O_NONBLOCK: 非阻塞模式打开
   14. O_SYNC: 对于write函数,等待文件描述符的物理写完成,文件属性被更新之后,才返回
   15. O_TRUNC: 如果文件是存在的,并且以write-only,read-write的方式打开,那么把文件内容截断为0
   16. O_TTY_INIT:
   17. O_DSYNC: 对于write函数,等待文件描述符的物理写完成就返回,但是不等待文件的属性更新
   18. O_RSYNC: 对于read函数,等待所有写完成再读
3. fd:
   1. 如果path是绝对路径名,fd被忽略
   2. 如果path是相对路径名,fd就会被用于确定起始地址
   3. 如果path是相对路径名,并且fd的值为AT_FDCWD,那么起始地址就是当前目录
每当我们打开一个新的文件,文件描述符的值为当前未使用的最小值.
比如,如果我们把 /STDOUT_FILENO/ 关闭,然后再打开一个新的文件,得到的文件描述符将是1
/opetat/ 函数用于解决两个问题
1. 它赋与了线程打开目录下的文件的能力,而不仅仅只是当前目录
2. 提供了一种方法来避免 time-of-check-to-time-of-use(TOCTTOU) 的错误
#+end_verse
*** +creat+
#+begin_verse
此函数只能写打开.现在直接用open函数代替了
#+end_verse
#+begin_src c
  #include <fcntl.h>
  int creat(const char *path, mode_t mode);
#+end_src
*** close
#+begin_verse
关闭一个文件描述符.关闭一个文件描述符同样会释放与这个文件相关的锁
当一个进程结束时,文件描述符会被操作系统自动释放.
#+end_verse
#+begin_src c
  #include <unistd.h>
  int close(int fd);
#+end_src
*** lseek
#+begin_verse
设置下一次读或写的文件偏移量.
通常我们使用open函数的时候,偏移量都为0,当我们使用open函数时指定了O_APPEND,偏移量是文件的末尾.
offset的值的意义由whence决定,whence由以下三种值
1. SEEK_SET: 起始偏移位置为文件开始位置
2. SEEK_CUR: 起始偏移位置为当前位置
3. SEEK_END: 起始偏移位置为文件末尾
offset为负表示向文件开始位置偏移,为正时往另一端偏移
该函数返回值为新的偏移量,所以当我们以offset为0来调用此函数,就会得到当前的偏移量.
如果fd代表的是一个pipe,FIFO或者socket,此函数返回1, /errno/ 被设置为 ESPIPE.
所以通常我们使用offset=0来调用此函数,如果返回-1,且errno为 ESPIPE 那么fd则是不能被 seek
如果当前的偏移量超过了文件末尾一段距离,当我们写入文件的时候,中间那一段距离会被 /空洞/ 填满
其实就是一堆 \0 并且它们不会占用磁盘空间
#+end_verse
#+begin_src c
  #include <unistd.h>
  off_t lseek(int fd, off_t offset, int whence);
#+end_src
*** read
#+begin_verse
从文件读n个字节,保存在buf中.返回值为读到的字节数.返回值有可能小于nbytes,也有可能为0,取决于读文件时的偏移量.
#+end_verse
#+begin_src c
  #include <unistd.h>
  ssize_t read(int fd, void *buf, size_t nbytes);
#+end_src
*** write
#+begin_verse
写入文件,其返回值同nbytes,表示写入的字节数,否则会报错.
#+end_verse
#+begin_src c
  #include <unistd.h>
  ssize_t write(int fd, const void *buf, size_t nbytes);
#+end_src
*** pread 与 pwrite
#+begin_src c
  #include <unistd.h>
  ssize_t pread(int fd, void *buf, size_t nbytes, off_t offset);
  ssize_t pwrite(int fd, const void *buf, size_t nbytes, off_t offset);
#+end_src
#+begin_verse
调用pread等同于 lseek + read 的原子操作.pwrite亦然.
#+end_verse
*** dup 与 dup2
#+begin_src c
  #include <unistd.h>
  int dup(int fd);
  int dup2(int fd, int fd2);
#+end_src
#+begin_verse
dup函数复制一个fd.
dup2复制fd,并为其文件描述符赋值为fd2.
如果fd2已经是打开的,那么就先关闭它.
如果fd与fd2是相同的,则不用关闭fd2,直接返回.
另外fd2的FD_CLOEXEC位被清除.
两个函数都返回新的文件描述符.
新旧的文件描述符共享了相同的 *文件表项* 他们也就共享了文件的偏移量
#+end_verse
*** sync,fsync,fdatasync
#+begin_src c
  #include <unistd.h>
  int fsync(int fd);
  int fdatasync(int fd);
  void sync(void);
#+end_src
#+begin_verse
当我们调用write函数的时候,只是写入的操作系统的buffer中,并没有真正写入磁盘.
sync函数的作用是把buffer放入待写入磁盘的队列里,然后返回,加快了写入磁盘
fdatasync只作用于单个文件描述符,它会等到文件内容写入到磁盘才返回
fsync除了等到文件内容写入文件以外,还会等待文件属性的更新才返回
#+end_verse
*** fcntl
#+begin_src c
  #include <fcntl.h>
  int fcntl(int fd, int cmd, ... /* int arg */);
#+end_src
#+begin_verse
fcntl函数主要作用为以下几个方面
1. 复制文件描述符: cmd = F_DUPFD 或者 F_DUPF_CLOEXEC
2. 获得/设置文件的描述符旗标: cmd = F_GETFD 或者 F_SETFD
3. 获得/设置文件的状态旗标: cmd = F_GETFL 或者 F_SETFL
4. 获得/设置文件异步IO的所有者: cmd = F_GETOWN 或者 F_SETOWN
5. 获得/设置记录锁: cmd = F_GETLK,F_SETLK,F_SETLKW

1. F_DUPFD: 复制fd,返回新的文件描述符.fd与newfd共享同一个文件表项.但是有自己的文件描述符旗标.newfd的FD_CLOEXEC是被清除的
2. F_DUPFD_CLOEXEC: 同上,只是FD_CLOEXEC会被置位
3. F_GETFD: 返回旗标,目前只有FD_CLOEXEC
4. F_SETFD: 设置旗标,旗标的值由最后一个参数决定
5. F_GETFL: 返回文件描述符的旗标 [[*open 与 openat][flags]]
    由于某些历史原因,对于 O_RDONLY,O_WRONLY,O_RDWR,O_EXEC,O_SEARCH 需要先与O_ACCMODE 做 位与运算,然后再与这5个值做比较
6. F_SETFL: 设置文件描述符的旗标.当调用open函数后,只能通过此方法来修改oflag的值.只有以下几个值能修改
    O_APPEND,O_NONBLOCK,O_SYNC,O_SYNC,O_RSYNC,O_FSYNC,O_ASYNC
7. F_GETOWN: 返回当前接收 SIGIO和SIGURG 信号的进程ID或进程组ID
8. F_SETOWN: 设置接收 SIGIO和SIGURG 信号的进程ID或进程组ID.用正数表示进程ID,用负数表示(负数的绝对值)进程组ID.

关于函数的返回值:
1. F_DUPFD: 返回新的文件描述符
2. F_GETFD,F_GETFL: 返回相应的旗标
3. F_GETOWN: 返回正数表示进程ID,负数表示进程组ID,使用时要使用它的绝对值.
#+end_verse
*** 包罗万象的ioctl
#+begin_src c
  #include <unistd.h> /* System V */
  #include <sys/ioctl.h> /* BSD and Linux */
  int ioctl(int fd, int request, ...);
#+end_src
* 文件与目录
** stat 函数们
#+begin_src c
  #include <sys/stat.h>
  int stat(const char *restrict pathname, struct stat *restrict buf);
  int fstat(int fd, struct stat *buf);
  int lstat(const char *restrict pathname, struct stat *restrict buf);
  int fstatat(int fd, const char *restrict pathname, struct stat *restrict buf, int flag);
#+end_src

#+begin_verse
1. stat: 返回pathname指向的文件的属性
2. fstat: 返回已打开的文件的属性
3. lstat: 同stat,只不过,当pathname是一个链接的时候,返回链接本身的属性,而不会引用到原始文件
4. fstatat: 返回文件的属性.
   1. flag: 当其值为AT_SYMLINK_NOFOLLOW时,返回链接文件的属性,否则返回原始文件的属性
   2. 如果pathname为绝对路径,fd被忽略
   3. 如果fd的值为AT_FDCWD,那么pathname的起始目录为当前目录
   4. 如要pathname为相对路径,那么pathname为相对于fd的路径
5. buf: 保存文件属性的结构体

stat结构体如下:
#+end_verse
#+begin_src c
  struct stat {
      // file type and mode
      mode_t st_mode;
      // i-node number
      ino_t st_ino;
      // device number
      dev_t st_ev;
      // device number for special files
      dev_t st_rdev;
      // 链接的数量
      nlink_t st_nlink;
      // 所属者ID
      uid_t st_uid;
      // 所属组ID
      gid_t st_gid;
      // 普通文件时,表示文件的大小
      off_t st_size;
      // 最后一次访问时间
      struct timespec st_atim;
      // 最后一次修改时间
      struct timespec st_mtim;
      // 最后一次状态改变时间
      struct timespec st_ctim;
      // 最优 I/O 大小
      blksize_t st_blksize;
      // 文件一共被分配了多少个块
      blkcnt_t st_blocks;
  };

  struct timespec {
      // 秒
      time_t tz_sec;
      // 毫秒
      long tv_nsec;
  }

#+end_src
** 文件类型
#+begin_verse
1. 普通文件
2. 目录文件
3. 块特殊文件: 提供 带缓冲的访问 某一设备的 大小固定的块 的文件
4. 字符特殊文件: 提供 不带缓冲的访问 某一设备的 大小不固定的块 的文件
5. FIFO: 用于进程间交换信息的文件
6. Socket: 网络间进程交换信息的文件
7. Symbolic link: 链接文件
文件类型保存在 st_mode 中,用以下宏使用st_mode作为参数来判断文件的类型
   1. S_ISREG: 是不是普通文件
   2. S_ISDIR: 是不是目录
   3. S_ISCHR: 是不是字符特殊文件
   4. S_ISBLK: 是不是块特殊文件
   5. S_ISFIFO: 是不是pipe或者FIFO
   6. S_ISLNK: 是不是链接文件
   7. S_ISSOCK: 是不是socket
还有几种特殊类型的IPC对象用以下三个函数来做判断,使用 stat 结构体的指针作参数:
   1. S_TYPEISMQ: 是不是 消息队列对象
   2. S_TYPEISSEM: 是不是 信号量对象
   3. S_TYPEISSHM: 是不是 共享内存对象
有些旧的系统并没有提供这些宏,就需要我们自己定义.在 sys/stat.h 中可以看到 S_ISDIR的定义类似于
   =#define S_ISDIR(mode) (((mode) & S_IFMT) == S_IFDIR)= S_IFxxx表示相应的类型. S_IFMT则为类型掩码
#+end_verse
* 设置uid 与 设置gid
#+begin_verse
一个 *进程* 有多个相关的ID
#+end_verse
| real user ID            | Who we really are                      |
| real group ID           |                                        |
|-------------------------+----------------------------------------|
| effective user ID       |                                        |
| effective group ID      | used for file access permission checks |
| supplementary group IDS |                                        |
|-------------------------+----------------------------------------|
| saved set-user-ID       | saved by *exec* functions (See 8.11)   |
| saved set-group-ID      |                                        |
#+begin_verse
real ID: 用于确定启动进程的人究竟是谁
effective ID: 当进程要访问文件的时候,用 effective ID 来判断这个进程有没有权利访问文件
saved ID: 保存了 effective ID. saved-user-ID保存了effective-user-ID

st_mode中有个set-user-ID位和set-group-ID位,用于控制effective-ID
当用户A执行文件X,启动了一个进程P.P访问文件M.使用P的effective-ID来判断P有没有权限访问M.A有权限修改M,P进程能顺利完成工作
这个时候real-user-ID => A, effective-user-ID => A
然后用户B执行文件X,启动了一个进程P2,P2同样会访问文件M,但是B没有权限访问M,P2不能完成工作
这个时候real-user-ID => B, effective-user-ID => B
如果把X的st_mode,set-user-ID位 置位 , 那么对于P2,它的effective-user-ID位就会变成A.P2就能顺序完成工作.

比如修改密码的passwd命令,它会修改/etc/passwd文件,普通用户是没有权限修改这个文件的,
但是普通用户却能修改自己的密码,就是因为passwd,这个可执行文件的set-user-ID位被置位了,它临时拥有了root用户的权限.才可以修改/etc/password

在写程序的时候,可以使用 seteuid 这个函数来设置启动的这个进程的 effective-user-ID.
然后执行这个程序,这个程序就能获得这个uid用户的文件访问权限
#+end_verse
* 文件访问权限
#+begin_verse
一个文件有9种基本权限.一共分为三组,分别代表 文件拥有者 文件所属组 其它用户 如:
=-rw-rw-r--  1 inmove inmove  13K Nov  8 13:10 emacs.org=
第一个 '-' 表示的是文件类型, '-' 表示普通文件,'d'文件目录,'l'表示链接文件
前三个 'rw-' 分别表示 文件拥有者的 读(r),写(w),执行(x).'-'表示没有这个权限
中间三个 'rw-' 为文件所属组
最后三个 'r--' 为其它用户
我们可以使用 chmod 命令来修改文件的访问权限,这个后面会说到.
#+end_verse
| st_mode mask | Meaning       |
|--------------+---------------|
| S_IRUSR      | user-read     |
| S_IWUSR      | user-write    |
| S_IXUSR      | user-execute  |
|--------------+---------------|
| S_IRGRP      | group-read    |
| S_IWGRP      | group-write   |
| S_IXGRP      | group-execute |
|--------------+---------------|
| S_IROTH      | other-read    |
| S_IWOTH      | other-write   |
| S_IXOTH      | other-execute |

** 文件访问权限对于文件的意义
#+begin_verse
1. 普通文件:
   1. r,表示可以读这个文件,可以使用cat等命令查看基内容.另外,想要读一个文件,还要有文件所在目录的x权限
   2. w,表示可以往这个文件中写内容
   3. x,表示可以执行这个文件.至于如何执行这个文件则和文件的内容以及shebang有关
2. 目录文件: 把目录想像成普通文件 通过ls看到的内容就是这个文件的内容,要用w才能增加,删除,重命令目录下的文件.
   1. r,表示可以查看目录中的文件名.如果没有对于目录的r权限,ls就直接返回permission denied
   2. w,表示可以在目录中删除,修改文件名
   3. x,表示可以进入这个目录.所以对于普通文件,必须要有这个文件所在目录的x权限,才有读或者修改普通文件的内容.不然的话连进入这个目录的权限都没有,更不要说修改目录下的文件的内容了
#+end_verse
* 测试访问权限
#+begin_verse
前面说了,一个进程要访问一个文件的时候,会用effective-ID去测试这个进程有没有权限访问这个文件.
Linux又提供了另外两个函数来测试real-ID的权限
#+end_verse
#+begin_src c
  #include <unistd.h>
  int access(const char *pathname, int mode);
  int faccessat(int fd, const char *pathname, int mode, int flag);
#+end_src
#+begin_verse
pathname可以是相对路径也可以是绝对路径.
对于faccessat函数:
1. 如果pathname为绝对路径,没有什么特别的,按照绝对路径去找文件就行了
2. 如果pathname为相对路径,fd的值为AT_FDCWD,那么就在当前路径下去找这个pathname
3. 如果pathname为相对路径,以fd所在的目录为起始目录去找这个pathname

flag表示需要测试的是什么访问权限,例如想要测试读写权限则用 R_OK | W_OK.另外,如果flag的AT_EACCESS被置位,那么就会用effective-ID去做测试
#+end_verse
| mode | description                 |
|------+-----------------------------|
| R_OK | test for read permission    |
| W_OK | test for write permission   |
| X_OK | test for execute permission |
* 文件相关的函数
** umask
#+begin_src c
  #include <sys/stat.h>
  mode_t umask(mode_t cmask);
#+end_src
#+begin_verse
用O_CREAT调用open函数的时候,创建的文件的权限位一般为644,使用umask命令可以返回002.002的意思就是屏蔽掉 S_IWOTH 位.
当我们创建文件或者目录的时候,权限位就为 777 - 002.创建文件为 644,所以touch命令应该是有更新这个默认的umask值的.
#+end_verse
** chmod, fchmod 与 fchmodat
#+begin_src c
  #include <sys/stat.h>

  int chmod(const char *pathname, mode_t mode);
  int fchmod(int fd, mode_t mode);
  int fchmodat(int fd, const char *pathname, mode_t mode, int flag);
#+end_src
#+begin_verse
chmod类函数用于修改文件的访问权限
chmod用于修改pathname指定的文件,fchmod用于修改已打开的文件
对于fchmodat函数
  1. 当pathname为绝对路径时,fd被忽略
  2. 当pathname为相对路径,fd为AT_FDCWD时,pathname的起始路径为当前路径
  3. 当pathname为相对路径,fd不为AT_FDCWD时,pathname的起始路径为fd所在目录
  4. 当pathname为链接文件时,默认会跟随链接文件使用原目标文件,当flag值为 AT_SYMLINK_NOFOLLOW 时,则不跟随到原文件
这几个函数有没有权限修改这个文件,需要检查的是 effective-ID.
mode有以下一些值
#+end_verse
#+begin_verse
1. S_ISUID: pathname指向的文件执行时的set-user-ID位被置位
2. S_ISGID
3. S_ISVTX: [[*粘滞位][粘滞位]]
4. S_IRWXU: 文件拥有者的 读,写,执行 权限
5. S_IRUSR: 拥有者的读权限
6. S_IWUSR
7. S_IXUSR
8. S_IRWXG: 文件所属组的 读写执行权限
9. S_IRGRP
10. S_IWGRP
11. S_IX_GRP
12. S_IRWXO
13. S_IROTH
14. S_IWOTH
15. S_IXOTH
#+end_verse
** chown fchown fchownat lchown
#+begin_src c
  #include <unistd.h>
  int chown(const char *pathname, uid_t owner, gid_t group);
  int fchown(int fd, uid_t owner, gid_t group);
  int fchownat(int fd, const char *pathname, uid_t owner, gid_t group, int flag);
  int lchown(const char *pathname, uid_t owner, gid_t group);
#+end_src
** truncate ftruncate
#+begin_src c
  #include <unistd.h>
  int truncate(const char *pathname, off_t length);
  int ftruncate(int fd, off_t length);
#+end_src
#+begin_verse
这两个函数都用于把文件截断到length大小
如果文件本身比length要大,那么大于length部分将无法访问
如果文件本身比length要小,那么中间将被 \0 填满
用O_TRUNC来open一个文件的时候相当于把length设置为0
#+end_verse
** link linkat unlink unlinkat remove
#+begin_src c
  #include <unistd.h>
#+end_src
* 粘滞位
#+begin_verse
用 t 表示粘滞位,如下表示其它用户对 tmp目录拥有粘滞位权限,粘滞位是目录特有的权限位.
如果一个目录带粘滞位,那么相应的用户在这个目录下面创建的文件只有这个用户才有更改的权限
当然这个用户对这个带粘滞位的目录具有可执行权限才能进到这个目录下面去.
#+end_verse
#+begin_example
  drwxrwxrwt  17 root root 4.0K Nov 25 22:59 tmp
#+end_example
